// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpjPbVzv1doRk7y5zsSiFTvYZNn6brcZc',
    appId: '1:961732200215:web:10a894c12ece1a65585952',
    messagingSenderId: '961732200215',
    projectId: 'caducidapp',
    authDomain: 'caducidapp.firebaseapp.com',
    storageBucket: 'caducidapp.firebasestorage.app',
    measurementId: 'G-P766X48NCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrbVLgSVdngqkDaqz39y9didOEjGxnbY',
    appId: '1:961732200215:android:f6949739082ab897585952',
    messagingSenderId: '961732200215',
    projectId: 'caducidapp',
    storageBucket: 'caducidapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_wyUteQwN6V2GzQnBhanxXw8BVzNLgw',
    appId: '1:961732200215:ios:07412cc4a2120a56585952',
    messagingSenderId: '961732200215',
    projectId: 'caducidapp',
    storageBucket: 'caducidapp.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpjPbVzv1doRk7y5zsSiFTvYZNn6brcZc',
    appId: '1:961732200215:web:b7b1b6e73995e0c0585952',
    messagingSenderId: '961732200215',
    projectId: 'caducidapp',
    authDomain: 'caducidapp.firebaseapp.com',
    storageBucket: 'caducidapp.firebasestorage.app',
    measurementId: 'G-11ZWJVETH3',
  );
}
